### ISSUE TITLE
Support for Auto-Registering Event Subscribers

### ISSUE THREAD

**Issue by mtotheikle** [KnpLabs/KnpRadBundle#182]
Has anyone thought of this idea so that the following snippet is not required in a service file?

``` yaml
services:
    acme_demo.some.listener:
        class: %acme_demo.some.listener.class%
        tags:
            - { name: kernel.event_subscriber }
```

Is this functionality already there and I'm just overlooking it?
