### ISSUE TITLE
createAccessDeniedException() must be public

### ISSUE THREAD

**Issue by gaetan-petit** [KnpLabs/KnpRadBundle#189]
I'm installing a project with KnpRadBundle.

I'm not able to make it run unless the visibilty of this method in 
/vendor/knplabs/rad-bundle/Knp/RadBundle/Controller/Controller.php on line 11 
is set to public.

**Comment by docteurklein** [comment]
Unfortunalty, symfony base controller (which we extend, which is bad) sets the visibility of this method to public (which is totally strange IMHO, because no one should call this method from the outside). 

This statment is true for all other helper methods (generateUrl, renderResponse, ...)
Anyway, unless symfony makes changes in their own base controller (which I doubt), we will have to do something.

the easier is to not override this method in our base class (simply remove it), or if we keep it, make it public, as you proposed).
It's a quick fix and if you want to provide a PR, please do :) would be awesome.

Otherwise, the other cleaner solution is to not use a base controller, but instead compose your own class and inject only the helpers you want.

There is one for rendering responses, another one for routing, another one for security, ...
and you can make your owns.

example:

``` yaml

services:

    app.controller.inscription:
        class: App\Controller\InscriptionController
        arguments:
            - '@form.factory'
            - '@knp_rad.controller.helper.doctrine'
            - '@knp_rad.controller.helper.session'
            - '@knp_rad.controller.helper.response'


```

this would be the best approach (to my mind). It's called "controller as a service".

Anyway, it doesn't resolve the inheritance problem raised here, we have to fix this visiblity problem.

Thanks for pointing this out!
