### ISSUE TITLE
[Assetic Pipeline] Allow to define custom dirs for types

### ISSUE THREAD

**Issue by aldesantis** [KnpLabs/KnpRadBundle#22]
I'm using Bootstrap with my project, and decided to clone it and use the LESS version.

So, I added the dependency to my **composer.json** (I had to define a new repository since Bootstrap isn't available natively through Composer), and modified my **knp_rad.yml** as follows:

```
all:
    # ...

    assetic_pipeline:
        enabled:  true
        paths:
            - %kernel.project_dir%/Resources/public
            - %kernel.project_root%/assets
            - %kernel.project_root%/vendor/twitter/bootstrap

    # ...
```

Then, I created a new **style.css** that contained the following:

```
/*
 *= require libs/boilerplate
 *= require bootstrap
 */
```

But I get an error because Assetic Pipeline looks for the dependency in **vendor/twitter/bootstrap/css/**, while it should look under **vendor/twitter/bootstrap/less**.

It'd be nice if I could define additional sub-directories to look in when resolving dependency, e.g..:

```
all:
    # ...

    assetic_pipeline:
        # ...
        types:
            css: ["css", "less", "sass", "scss"]
            js: ["js", "coffee"]

    # ...
```

What do you think?
