### ISSUE TITLE
can't remove all resources from routing

### ISSUE THREAD

**Issue by oste** [KnpLabs/KnpRadBundle#52]
Is there a way to remove all resource routes? I thought something like this might work.

```
App:Test:
    collections: 
        index: ~
        custom:
            pattern: /custom/
    resources: ~
```

But I am still getting the following routes when running `router:debug`

I also tried `resources: []` and `resources: {}`, which produced the same results

app_test_show                  GET      /test/{id}
app_test_edit                    GET      /test/{id}/edit
app_test_update               PUT      /test/{id}
app_test_delete                DELETE   /test/{id}
